#! python

# Initialize the environment
env = Environment(CPPFLAGS='-I/usr/local/mdsplus/include') 

#mdsclient = env.SharedLibrary(target='mdsclient', source='mdsclient.c', \
#		LIBS='MdsIpShr', LIBPATH='/usr/local/mdsplus/lib')

libs_static = [File('/usr/local/mdsplus/lib/libMdsIpShr.a'), File('/usr/local/mdsplus/lib/libMdsIpUtil.a')]
mdsclient = env.SharedLibrary(target='mdsclient', source='mdsclient.c', LIBS=libs_static)


env.Program(target='mdsclient_test', source='mdsclient_test.c', LIBS=mdsclient)


