#! python
import distutils.sysconfig as sc
CFLAGS = sc.get_config_var('CFLAGS')
LDFLAGS = sc.get_config_var('LDFLAGS')

F90FLAGS = ''.join([CFLAGS, ' -fno-underscoring'])

# Initialize the environment
env = Environment(F90FLAGS=F90FLAGS, LINKFLAGS=LDFLAGS) 

env.SharedLibrary(target = 'specfun', source = 'specfun.f90')
